export const RETRIEVE_TOP_PLAYERS_REQUEST = 'RETRIEVE_TOP_PLAYERS_REQUEST';
export const RETRIEVE_TOP_PLAYERS_SUCCESS = 'RETRIEVE_TOP_PLAYERS_SUCCESS';
export const RETRIEVE_TOP_PLAYERS_FAILURE = 'RETRIEVE_TOP_PLAYERS_FAILURE';

export const RETRIEVE_LATEST_POLLS_REQUEST = 'RETRIEVE_LATEST_POLLS_REQUEST';
export const RETRIEVE_LATEST_POLLS_SUCCESS = 'RETRIEVE_LATEST_POLLS_SUCCESS';
export const RETRIEVE_LATEST_POLLS_FAILURE = 'RETRIEVE_LATEST_POLLS_FAILURE';

export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';

export const ANSWER_POLL_REQUEST = 'ANSWER_POLL_REQUEST';
export const ANSWER_POLL_SUCCESS = 'ANSWER_POLL_SUCCESS';

export const REFRESH_TOP_SCORES = 'REFRESH_TOP_SCORES';

export const RESET_SCOREBOARD = 'RESET_SCOREBOARD';

export const RESET_POLLS = 'RESET_POLLS';

export const REFRESH_LATEST_POLLS = 'REFRESH_LATEST_POLLS';

export const ADD_NEW_USER = 'ADD_NEW_USER';

export const ADD_NEW_POLL = 'ADD_NEW_POLL';

export const LOGOUT = 'LOGOUT';

export const SAVE_PROFILE = 'SAVE_PROFILE';

export const SELECT_PROFILE = 'SELECT_PROFILE';

export const SIGN_IN = 'SIGN_IN';

export const ANSWER_POLL = 'ANSWER_POLL';

export const SELECT_OPTION = 'SELECT_OPTION';

export const SELECT_POLL = 'SELECT_POLL';

export const SET_HEADER = 'SET_HEADER';

export const SET_POLLS = 'SET_POLLS';

export const SET_USER_PROFILES = 'SET_USER_PROFILES';

export const FINISH_LOADING = 'FINISH_LOADING';

export const CHANGE_FILTER = 'CHANGE_FILTER';
